[[system-image-loader]]
arch = "aarch64"
git-tree-sha1 = "28759362e92f9c1e7455182b1ab7b0b81af73ab0"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "b64bf65751ac8122e35fa6e8af6dbe101d5ebc3d624beb5221659ca4a99f3ac5"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-aarch64-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "i686"
git-tree-sha1 = "c0dd3c10b4cf915b7d3320b0af2a242954093812"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "35f3c08414f8169c30ba1e83ba2276fb21e85e53d0df0446aed9e2e413b929c7"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-i686-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "8f4e15acdeaf9e00f3a9cf49b8c19144a2995899"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "66418c32929de71124be20248bac6db79ef7f6c907490ed9824c2d96eeea1c30"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-x86_64-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "c1e8d8760599413145e33ae0b840ca02759e3d1f"
os = "macos"

    [[system-image-loader.download]]
    sha256 = "8fd8aaac609e579b9d4a5b7d2ca48e8885b24d7454b1264c0c2ed90dd556ffeb"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-x86_64-apple-darwin.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "921b90dd5d2693be6f6b138788afabf37b28b093"
os = "windows"

    [[system-image-loader.download]]
    sha256 = "a049495e1d967145fb5850753258ef686d3bc98c56587e62a0fa55d3adaecaf1"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-x86_64-pc-windows-gnu.tar.gz"
[[system-image-loader]]
arch = "aarch64"
git-tree-sha1 = "b4dd046d817c61f5c3729903eb93e5098f6d4d3a"
os = "macos"

    [[system-image-loader.download]]
    sha256 = "014f8caa61aff80af29a1900c9946819207887eeb28218bf6236018acf112fb8"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.0.1/system-image-loader-1.0.1-aarch64-apple-darwin.tar.gz"
