[[system-image-loader]]
arch = "aarch64"
git-tree-sha1 = "3b70f6512df891c5e18bc7a11ae375d2adab08e5"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "09edc35222afe25c56648d7971c1069d52215d0a28a40cc0efd4507bf8ca2509"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-aarch64-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "i686"
git-tree-sha1 = "c6218dfc041abf958512ae3764a96d1e0e70851d"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "3a0df287f8fb8e7bf0bcc427b605b702345094fc4a6f239e6d0b2abe6a13bc4f"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-i686-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "b8b1ad168aa24f9d6852fd90c088b7e48807ea60"
libc = "glibc"
os = "linux"

    [[system-image-loader.download]]
    sha256 = "c2ca4c17499d862d492655d8d11a13fb790a56b2ead02703b20bb95f6f4f606f"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-x86_64-unknown-linux-gnu.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "29cb0902dff4c40179e00c8cda31d49baddb8b5d"
os = "macos"

    [[system-image-loader.download]]
    sha256 = "26f60b2fc79051e02c027b547f1e4c2ce71dcb5695134d7164e0403fd85c8bf3"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-x86_64-apple-darwin.tar.gz"
[[system-image-loader]]
arch = "x86_64"
git-tree-sha1 = "b896a052600ce0c0d1d66ad688e74e7acff12540"
os = "windows"

    [[system-image-loader.download]]
    sha256 = "5d8072a448bf74fd5946596b19316f731a9ec94d92ec3cac14603928523feeaf"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-x86_64-pc-windows-gnu.tar.gz"
[[system-image-loader]]
arch = "aarch64"
git-tree-sha1 = "7cc6fb982cf311ae6a401152856e75680d03e771"
os = "macos"

    [[system-image-loader.download]]
    sha256 = "ff742a5a30b3f4475e4cb6f2820a1a7a1cc35d9e845a315478a7860291516307"
    url = "https://github.com/MichaelHatherly/system-image-loader/releases/download/v1.1.3/system-image-loader-1.1.3-aarch64-apple-darwin.tar.gz"
