name: Update Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Artifacts version to build.'
        required: true
        type: 'string'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
          arch: x64

      - name: Instantiate artifactutils environment
        run: julia --project=.artifactutils -e 'import Pkg; Pkg.instantiate()'

      - name: Update the artifacts
        run: julia --project=.artifactutils .artifactutils/update.jl ${{ inputs.version }}

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '🤖 Automatic update of `Artifacts.toml`.'
          title: '🤖 Automatic update of `Artifacts.toml`.'
          body: |-
            This pull request updates the `Artifacts.toml` to the latest versions.
          branch: bot/update-artifacts/${{ github.ref }}
          delete-branch: true
          add-paths: Artifacts.toml
